# Generated by Django 5.0.6 on 2024-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0004_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pub_date',
        ),
    ]
