# Generated by Django 5.0.6 on 2024-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
