# Generated by Django 5.0.6 on 2024-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0006_remove_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quizzez.question'),
        ),
    ]
