# Generated by Django 5.0.6 on 2024-06-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0013_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
